[package]
name = "todo"
version = "0.1.0"
authors = ["4afS <4afS.h1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
